name: op
version: 0.1.0
description: A Dart library defining interfaces for mathematical operations, such as addition and multiplication
repository: https://github.com/dkin-om/op.git
issue_tracker: https://github.com/dkin-om/op/issues
homepage: https://github.com/dkin-om/op#readme
environment:
  sdk: '>=2.12.0 <4.0.0'
dev_dependencies:
  equatable: ^2.0.5
  test: ^1.14.4
screenshots:
  - description: op package logo
    path: img/logo.png
funding:
  - https://github.com/sponsors/dkin-om
  - https://ko-fi.com/dkinom
